export const mockUsersData = [
    {
        id: 1,
        image: 'assets/img/project/chats-avatar.png',
        name: 'Jessica Drew',
        message: 'David Moore',
        time: '18:30',
        readMessageCount: '2',
        recentTime: 'last seen 5 mins ago',
    },
    {
        id: 2,
        image: 'assets/img/project/chats-avatar2.png',
        name: 'John Smith',
        message: 'Hello, how are you?',
        time: '17:45',
        readMessageCount: '5',
        recentTime: 'last seen 5 mins ago',
    },
    {
        id: 3,
        image: 'assets/img/project/chats-avatar3.png',
        name: 'Emily Johnson',
        message: 'Meeting at 3 PM',
        time: '16:20',
        readMessageCount: '1',
        recentTime: 'last seen 5 mins ago',
    },
    {
        id: 4,
        image: 'assets/img/project/chats-avatar4.png',
        name: 'Michael Brown',
        message: 'Can you send the report?',
        time: '15:10',
        readMessageCount: '0',
        recentTime: 'last seen 5 mins ago',
    },
    {
        id: 5,
        image: 'assets/img/project/chats-avatar5.png',
        name: 'Sarah Davis',
        message: 'Lunch tomorrow?',
        time: '14:00',
        readMessageCount: '3',
        recentTime: 'last seen 5 mins ago',
    },
    {
        id: 6,
        image: 'assets/img/project/chats-avatar6.png',
        name: 'David Wilson',
        message: 'Project update',
        time: '13:30',
        readMessageCount: '4',
        recentTime: 'last seen 5 mins ago',
    },
    {
        id: 7,
        image: 'assets/img/project/chats-avatar7.png',
        name: 'Laura Martinez',
        message: 'Call me when you can',
        time: '12:45',
        readMessageCount: '2',
        recentTime: 'last seen 5 mins ago',
    },
    {
        id: 8,
        image: 'assets/img/project/chats-avatar.png',
        name: 'James Anderson',
        message: 'Got it, thanks!',
        time: '11:50',
        readMessageCount: '1',
        recentTime: 'last seen 5 mins ago',
    },
    {
        id: 9,
        image: 'assets/img/project/chats-avatar2.png',
        name: 'Patricia Thomas',
        message: 'See you soon',
        time: '10:30',
        readMessageCount: '0',
        recentTime: 'last seen 5 mins ago',
    },
    {
        id: 1,
        image: 'assets/img/project/chats-avatar.png',
        name: 'Jessica Drew',
        message: 'David Moore',
        time: '18:30',
        readMessageCount: '2',
        recentTime: 'last seen 5 mins ago',
    },
    {
        id: 2,
        image: 'assets/img/project/chats-avatar2.png',
        name: 'John Smith',
        message: 'Hello, how are you?',
        time: '17:45',
        readMessageCount: '5',
        recentTime: 'last seen 5 mins ago',
    },
    {
        id: 3,
        image: 'assets/img/project/chats-avatar3.png',
        name: 'Emily Johnson',
        message: 'Meeting at 3 PM',
        time: '16:20',
        readMessageCount: '1',
        recentTime: 'last seen 5 mins ago',
    },
    {
        id: 4,
        image: 'assets/img/project/chats-avatar4.png',
        name: 'Michael Brown',
        message: 'Can you send the report?',
        time: '15:10',
        readMessageCount: '0',
        recentTime: 'last seen 5 mins ago',
    },
    {
        id: 5,
        image: 'assets/img/project/chats-avatar5.png',
        name: 'Sarah Davis',
        message: 'Lunch tomorrow?',
        time: '14:00',
        readMessageCount: '3',
        recentTime: 'last seen 5 mins ago',
    },
    {
        id: 6,
        image: 'assets/img/project/chats-avatar6.png',
        name: 'David Wilson',
        message: 'Project update',
        time: '13:30',
        readMessageCount: '4',
        recentTime: 'last seen 5 mins ago',
    },
    {
        id: 7,
        image: 'assets/img/project/chats-avatar7.png',
        name: 'Laura Martinez',
        message: 'Call me when you can',
        time: '12:45',
        readMessageCount: '2',
        recentTime: 'last seen 5 mins ago',
    },
    {
        id: 8,
        image: 'assets/img/project/chats-avatar.png',
        name: 'James Anderson',
        message: 'Got it, thanks!',
        time: '11:50',
        readMessageCount: '1',
        recentTime: 'last seen 5 mins ago',
    },
    {
        id: 9,
        image: 'assets/img/project/chats-avatar2.png',
        name: 'Patricia Thomas',
        message: 'See you soon',
        time: '10:30',
        readMessageCount: '0',
        recentTime: 'last seen 5 mins ago',
    },
];

export const mockSelectedUser = {
    id: 1,
    image: 'assets/img/project/chats-avatar.png',
    name: 'Jessica Drew',
    message: 'David Moore',
    time: '18:30',
    readMessageCount: '2',
    recentTime: 'last seen 5 mins ago',
};